version: '3.8'
services:
  api:
    restart: on-failure
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - sameNetworkAsMysql
    ports:
      - "5000:5000"

  frontend:
    restart: on-failure
    command: >
      sh -c "npm run dev -- --host"
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    networks:
      - sameNetworkAsMysql
    depends_on:
      - api

networks:
  sameNetworkAsMysql:
    driver: bridge
    ipam:
      config:
        - subnet: "172.18.0.0/16"
